program: GladstoneKeegan5.o getdouble.o
	gcc GladstoneKeegan5.o getdouble.o -o program -lm

GladstoneKeegan5.o: GladstoneKeegan5.c getdouble.h
	gcc -c GladstoneKeegan5.c

getdouble.o: getdouble.c getdouble.h
	gcc -c getdouble.c
	