program: GladstoneKeegan10.o getdouble.o
	gcc GladstoneKeegan10.o getdouble.o -o program -lm

GladstoneKeegan4.10: GladstoneKeegan10.c getdouble.h
	gcc -c GladstoneKeegan10.c

getdouble.o: getdouble.c getdouble.h
	gcc -c getdouble.c
	