program: GladstoneKeegan18.o creating.o getdouble.o writing.o reading.o
	gcc GladstoneKeegan18.o creating.o getdouble.o writing.o reading.o -o program -lm

GladstoneKeegan18.o: GladstoneKeegan18.c creating.h writing.h reading.h
	gcc -c GladstoneKeegan18.c



