program: GladstoneKeegan8.o getdouble.o
	gcc GladstoneKeegan8.o getdouble.o -o program -lm

GladstoneKeegan8.o: GladstoneKeegan8.c getdouble.h
	gcc -c GladstoneKeegan8.c

getdouble.o: getdouble.c getdouble.h
	gcc -c getdouble.c
	