program: GladstoneKeegan6.o getdouble.o
	gcc GladstoneKeegan6.o getdouble.o -o program -lm

GladstoneKeegan6.o: GladstoneKeegan6.c getdouble.h
	gcc -c GladstoneKeegan6.c

getdouble.o: getdouble.c getdouble.h
	gcc -c getdouble.c
	